# -*- coding: utf-8 -*-
"""生成 kjkfast.c: 从 engine.py 的 TOKENS 字符集生成 C 查表源码。"""
import sys, os

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ROOT, 'python'))
from engine import TOKENS, BASE

assert BASE == 20, BASE

def c_bytes(bs):
    return '{' + ', '.join(f'0x{b:02X}' for b in bs) + '}'

lines = []
lines.append('/* kjkfast.c — KJK Encryptor C 加速引擎 (token 编解码)')
lines.append(' * 自动生成: python tools/gen_kjkfast.py')
lines.append(' * 编译: gcc -O2 -shared -o kjkfast.dll kjkfast.c (或 cl /O2 /LD kjkfast.c)')
lines.append(' * 接口由 python/engine.py 通过 ctypes 调用; 缺失时自动回退 numpy/纯 Python。')
lines.append(' */')
lines.append('#include <stdint.h>')
lines.append('#include <stddef.h>')
lines.append('')
lines.append('/* 20 个 token 的 UTF-8 编码与字节长度 */')
rows = []
for ch in TOKENS:
    u = ch.encode('utf-8')
    rows.append(c_bytes(list(u)))
lines.append('static const uint8_t TOKEN_UTF8[20][4] = {')
for r in rows:
    lines.append(f'    {r},')
lines.append('};')
lines.append('')
lens = []
for ch in TOKENS:
    lens.append(str(len(ch.encode('utf-8'))))
lines.append(f'static const uint8_t TOKEN_LEN[20] = {{{", ".join(lens)}}};')
lines.append('')
lines.append('/* 每个字节 → 2 个 token 的 UTF-8 序列(最长 6 字节)与总长度 */')
lines.append('static uint8_t PAIR_BYTES[256][6];')
lines.append('static uint8_t PAIR_LEN[256];')
lines.append('')
lines.append('static void kjk_init_tables(void)')
lines.append('{')
lines.append('    static int inited = 0;')
lines.append('    if (inited) return;')
lines.append('    for (int b = 0; b < 256; b++) {')
lines.append('        int d0 = b % 20, d1 = b / 20;')
lines.append('        int p = 0;')
lines.append('        for (int k = 0; k < TOKEN_LEN[d0]; k++) PAIR_BYTES[b][p++] = TOKEN_UTF8[d0][k];')
lines.append('        for (int k = 0; k < TOKEN_LEN[d1]; k++) PAIR_BYTES[b][p++] = TOKEN_UTF8[d1][k];')
lines.append('        PAIR_LEN[b] = (uint8_t)p;')
lines.append('    }')
lines.append('    inited = 1;')
lines.append('}')
lines.append('')
lines.append('/* ASCII(1 字节) token → 序号, 0xFF 无效 */')
lines.append('static uint8_t ASCII_MAP[256];')
lines.append('')
lines.append('static void kjk_init_tables(void)')
lines.append('{')
lines.append('    static int inited = 0;')
lines.append('    if (inited) return;')
lines.append('    for (int i = 0; i < 256; i++) ASCII_MAP[i] = 0xFF;')
for i, ch in enumerate(TOKENS):
    u = ch.encode('utf-8')
    if len(u) == 1:
        lines.append(f'    ASCII_MAP[0x{u[0]:02X}] = {i};')
lines.append('    for (int b = 0; b < 256; b++) {')
lines.append('        int d0 = b % 20, d1 = b / 20;')
lines.append('        int p = 0;')
lines.append('        for (int k = 0; k < TOKEN_LEN[d0]; k++) PAIR_BYTES[b][p++] = TOKEN_UTF8[d0][k];')
lines.append('        for (int k = 0; k < TOKEN_LEN[d1]; k++) PAIR_BYTES[b][p++] = TOKEN_UTF8[d1][k];')
lines.append('        PAIR_LEN[b] = (uint8_t)p;')
lines.append('    }')
lines.append('    inited = 1;')
lines.append('}')
lines.append('')
lines.append('/* 3 字节 UTF-8 序列精确匹配 token 序号, 未命中返回 -1 */')
lines.append('static int kjk_lookup3(uint8_t b0, uint8_t b1, uint8_t b2)')
lines.append('{')
lines.append('    for (int t = 0; t < 20; t++) {')
lines.append('        if (TOKEN_LEN[t] == 3 && TOKEN_UTF8[t][0] == b0')
lines.append('            && TOKEN_UTF8[t][1] == b1 && TOKEN_UTF8[t][2] == b2) return t;')
lines.append('    }')
lines.append('    return -1;')
lines.append('}')
lines.append('')
lines.append('/* 字节 → token UTF-8 字符串。返回写入长度, 失败返回 -1。 */')
lines.append('long kjk_bytes_to_tokens(const uint8_t *in, size_t n, uint8_t *out, size_t cap)')
lines.append('{')
lines.append('    kjk_init_tables();')
lines.append('    if (cap < n * 6) return -1;')
lines.append('    size_t p = 0;')
lines.append('    for (size_t i = 0; i < n; i++) {')
lines.append('        uint8_t b = in[i];')
lines.append('        const uint8_t *pair = PAIR_BYTES[b];')
lines.append('        uint8_t len = PAIR_LEN[b];')
lines.append('        for (uint8_t k = 0; k < len; k++) out[p++] = pair[k];')
lines.append('    }')
lines.append('    return (long)p;')
lines.append('}')
lines.append('')
lines.append('/* token UTF-8 字符串 → 字节(忽略 ASCII 空白)。返回输出长度, 无效 token 返回 -1。 */')
lines.append('long kjk_tokens_to_bytes(const uint8_t *in, size_t n, uint8_t *out, size_t cap)')
lines.append('{')
lines.append('    kjk_init_tables();')
lines.append('    if (cap < n / 2 + 1) return -1;')
lines.append('    size_t p = 0;')
lines.append('    int have = 0;')
lines.append('    int d = 0;')
lines.append('    size_t i = 0;')
lines.append('    while (i < n) {')
lines.append('        uint8_t c = in[i];')
lines.append('        if (c == 0x20 || c == 0x09 || c == 0x0A || c == 0x0D) { i++; continue; }')
lines.append('        int v;')
lines.append('        if (c < 0x80) {')
lines.append('            v = ASCII_MAP[c];')
lines.append('            if (v == 0xFF) return -1;')
lines.append('            i++;')
lines.append('        } else {')
lines.append('            if (i + 2 >= n) return -1;')
lines.append('            v = kjk_lookup3(c, in[i + 1], in[i + 2]);')
lines.append('            if (v < 0) return -1;')
lines.append('            i += 3;')
lines.append('        }')
lines.append('        if (have == 0) { d = v; have = 1; }')
lines.append('        else {')
lines.append('            out[p++] = (uint8_t)((d + v * 20) & 0xFF);')
lines.append('            have = 0;')
lines.append('        }')
lines.append('    }')
lines.append('    if (have != 0) return -1; /* 落单 token */')
lines.append('    return (long)p;')
lines.append('}')
lines.append('')
lines.append('/* 引擎版本号, 便于 Python 侧探测 */')
lines.append('long kjkfast_version(void) { return 10400; }')

out_path = os.path.join(_ROOT, 'python', 'kjkfast.c')
with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(lines) + '\n')
print('written:', out_path)
